# name: upload my image to DockerHub

# on:
#   push:
#     branches: ['main', 'sivan-dev']
#   pull_request:
#     branches: ['main']

# env:
#   IMAGE_NAME: ofigu/math_exercise_app

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run actions/checkout@v4
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install Chrome
#         id: setup-chrome
#         uses: browser-actions/setup-chrome@v1

#       - name: Install deps
#         run: |
#           python -m pip install --upgrade pip
#           pip install selenium webdriver-manager

#       - name: Run Selenium Tests
#         env:
#           CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
#         run: |
#           python ./test_pass_gen.py

#   build:
#     runs-on: ubuntu-latest
#     needs: test
#     permissions:
#       contents: read
#     steps:
#       - name: Run actions/checkout@v4
#         uses: actions/checkout@v4

#       - name: Set up Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Docker metadata
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ env.IMAGE_NAME }}
#           tags: |
#             type=ref,event=branch
#             type=ref,event=pr
#             type=sha
#             type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

#       - name: Build
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

name: upload my image to DockerHub

on:
  push:
    branches: ['main', 'sivan-dev']
  pull_request:
    branches: ['main']

env:
  IMAGE_NAME: ofigu/math_exercise_app

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Selenium Tests
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          python ./test_pass_gen.py

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
